<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LawCaseManagementSystem.Application/LawCaseManagementSystem.Application.csproj" />
    <ProjectReference Include="../LawCaseManagementSystem.Domain/LawCaseManagementSystem.Domain.csproj" />
    <ProjectReference Include="../LawCaseManagementSystem.Shared/LawCaseManagementSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.21">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="8.0.21" />
  </ItemGroup>

</Project>
