<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="../LawCaseManagementSystem.Domain/LawCaseManagementSystem.Domain.csproj" />
    <ProjectReference Include="../LawCaseManagementSystem.Shared/LawCaseManagementSystem.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ReferenceData/DTOs/" />
    <Folder Include="ReferenceData/Services/" />
  </ItemGroup>

</Project>
